import { Geist, Geist_Mono } from 'next/font/google';
import type { ReactNode } from 'react';
import './globals.css';
import App from './components/Layout/Layout';
import '@ant-design/v5-patch-for-react-19';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <head>{/* Metadata should go here */}</head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <App>
          <main style={{ padding: '20px' }}>{children}</main>
        </App>
      </body>
    </html>
  );
}
